### ISSUE TITLE
License issue should be noticed when you copy code from lilien1010/lua-resty-maxminddb

### ISSUE THREAD

**Issue by lilien1010** [anjia0532/lua-resty-maxminddb#25]
when I checked your source code, I see a better code style with more fretures, I really liked it.
but also I am very familiar with your project while some source code is I think copied from my project `https://github.com/lilien1010/lua-resty-maxminddb` which is already licensed with Apache LISENCE.

Eg:
there is a comment like `https://www.maxmind.com/en/geoip2-databases  you should download  the mmdb file from maxmind`  is exactly from my project [lua-resty-maxminddb](https://github.com/lilien1010/lua-resty-maxminddb) 

According to the former opensource LISENCE is already Apache lisenced, BSD lisence is not acceptable.

**Comment by lilien1010** [comment]
If the license protocol is not followed, and this project is used in your company product or service , which will lead a legal issue.

**Comment by anjia0532** [comment]
Sorry, English is not my native language, this is translated via google.

I once searched the library about openresty+maxminddb from the Internet, including https://github.com/lilien1010/lua-resty-maxminddb that you open sourced, but it can’t meet my requirements (return only area information), and memory leak.
So I refer to your project (https://github.com/lilien1010/lua-resty-maxminddb) and libmaxminddb (https://github.com/maxmind/libmaxminddb), and express my gratitude in the reference area ( https://github.com/anjia0532/lua-resty-maxminddb#references)

The following is the part of the code I have copied from you (if any omissions, please point out), I am very sorry for the trouble caused by my infringement.

https://github.com/lilien1010/lua-resty-maxminddb/blob/f96633e2428f8f7bcc1e2a7a28b747b33233a8db/resty/maxminddb.lua#L5-L12 vs https://github.com/anjia0532/lua-resty-maxminddb/blob/cb0218352f553fce612cf914f0a5159930927b67/lib/resty/maxminddb.lua#L3-L10

https://github.com/lilien1010/lua-resty-maxminddb/blob/f96633e2428f8f7bcc1e2a7a28b747b33233a8db/resty/maxminddb.lua#L36-L126 vs https://github.com/anjia0532/lua-resty-maxminddb/blob/d98b71a714862ffd59344c6e43f655a54298d17d/lib/resty/maxminddb.lua#L23-L113

https://github.com/lilien1010/lua-resty-maxminddb/blob/f96633e2428f8f7bcc1e2a7a28b747b33233a8db/resty/maxminddb.lua#L136-L138 vs https://github.com/anjia0532/lua-resty-maxminddb/blob/d98b71a714862ffd59344c6e43f655a54298d17d/lib/resty/maxminddb.lua#L155-L157

https://github.com/lilien1010/lua-resty-maxminddb/blob/f96633e2428f8f7bcc1e2a7a28b747b33233a8db/resty/maxminddb.lua#L159-L176 vs https://github.com/anjia0532/lua-resty-maxminddb/blob/d98b71a714862ffd59344c6e43f655a54298d17d/lib/resty/maxminddb.lua#L312-L327

https://github.com/lilien1010/lua-resty-maxminddb/blob/master/resty/maxminddb.lua#L208 vs https://github.com/anjia0532/lua-resty-maxminddb/blob/master/lib/resty/maxminddb.lua#L349

https://github.com/lilien1010/lua-resty-maxminddb/blob/master/README.md#bug-reports vs https://github.com/anjia0532/lua-resty-maxminddb/blob/master/README.md#bug-reports

Measures taken in this regard:

1. Mark `-- copy from xxx` in the form of comments in the source code section (completed)
2. Describe this issue in README.md (completed)
3. Modify the license (I don't know much about Apache and BSD, if you are willing to help me, please help me) (unfinished)

The following is the original Chinese

    以下是中文原文
    对不起,英语不是我的母语,这是通过google翻译的.

    我曾经从网络上搜索关于openresty+maxminddb的库，其中包括你所开源的 https://github.com/lilien1010/lua-resty-maxminddb ,但是它不能满足我的要求(只返回区域信息),以及内存泄露.
    所以我参考了你的项目(https://github.com/lilien1010/lua-resty-maxminddb)和 libmaxminddb的(https://github.com/maxmind/libmaxminddb) , 并在引用区域对此表达谢意(https://github.com/anjia0532/lua-resty-maxminddb#references)

    以下是我列出的复制自您的代码部分(如有遗漏,请指出),针对我的侵权不当行为对您造成的困扰我感到十分抱歉.

    https://github.com/lilien1010/lua-resty-maxminddb/blob/f96633e2428f8f7bcc1e2a7a28b747b33233a8db/resty/maxminddb.lua#L5-L12 vs https://github.com/anjia0532/lua-resty-maxminddb/blob/cb0218352f553fce612cf914f0a5159930927b67/lib/resty/maxminddb.lua#L3-L10

    https://github.com/lilien1010/lua-resty-maxminddb/blob/f96633e2428f8f7bcc1e2a7a28b747b33233a8db/resty/maxminddb.lua#L36-L126 vs https://github.com/anjia0532/lua-resty-maxminddb/blob/d98b71a714862ffd59344c6e43f655a54298d17d/lib/resty/maxminddb.lua#L23-L113

    https://github.com/lilien1010/lua-resty-maxminddb/blob/f96633e2428f8f7bcc1e2a7a28b747b33233a8db/resty/maxminddb.lua#L136-L138 vs https://github.com/anjia0532/lua-resty-maxminddb/blob/d98b71a714862ffd59344c6e43f655a54298d17d/lib/resty/maxminddb.lua#L155-L157

    https://github.com/lilien1010/lua-resty-maxminddb/blob/f96633e2428f8f7bcc1e2a7a28b747b33233a8db/resty/maxminddb.lua#L159-L176 vs https://github.com/anjia0532/lua-resty-maxminddb/blob/d98b71a714862ffd59344c6e43f655a54298d17d/lib/resty/maxminddb.lua#L312-L327

    https://github.com/lilien1010/lua-resty-maxminddb/blob/master/resty/maxminddb.lua#L208 vs https://github.com/anjia0532/lua-resty-maxminddb/blob/master/lib/resty/maxminddb.lua#L349

    https://github.com/lilien1010/lua-resty-maxminddb/blob/master/README.md#bug-reports vs https://github.com/anjia0532/lua-resty-maxminddb/blob/master/README.md#bug-reports

    对此采取的措施:

    1. 在源码部分以注释的形式标明 `-- copy from xxx` (已完成)
    2. 在 README.md 说明此问题(已完成)
    3. 修改License(我对Apache和BSD的了解不多,如果您愿意帮助我的话,请帮帮我)(未完成)

**Comment by lilien1010** [comment]
I am not being criticism your better library for openresty community, just want you know that obey of open source licence will help the community go far and safe.

![image](https://user-images.githubusercontent.com/3814966/89500623-99c46b00-d7f4-11ea-9c0b-1c2a4bdca278.png)

please reference https://github.com/apache/apisix/blob/master/LICENSE
and change your LICENSE description in README.md,
and also I am PMC of Apache APISIX, feel free to join us and make a better API gateway.

**Comment by anjia0532** [comment]
done!

https://github.com/anjia0532/lua-resty-maxminddb/blob/master/LICENSE

**Comment by lilien1010** [comment]
@anjia0532 great ！
